### ISSUE TITLE
Collection:asMusicalNotation breaks nested arrays

### ISSUE THREAD

**Issue by jamshark70** [lvm/MusicalNotation#1]
```
[0.5, [0, -2, -5]].asMusicalNotation
-> 0.5
```

https://github.com/lvm/MusicalNotation/blob/master/Classes/extMethods.sc#L60

```
^(item.isRest.not).if...
```

This is already inside of `^this.collect` -- the method should only return the result of `collect` -- you don't want to exit early from this loop and return the `if` result for a single item.

Remove the extraneous `^` and it will work correctly.

Reported at https://scsynth.org/t/specifying-pitch-and-duration-in-pbind/2113

**Comment by lvm** [comment]
Thanks!
